version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tourguide
      - POSTGRES_USER=tourguide
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: python3 backend/tourguide/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=tourguide
      - POSTGRES_USER=tourguide
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
    environment:
      - VUE_APP_BASE_URL=http://0.0.0.0:8000
    volumes:
      - '.:/app'
    command: /bin/sh -c "yarn serve"
