version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tourguide
      - POSTGRES_USER=tourguide
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 tourguide/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=tourguide
      - POSTGRES_USER=tourguide
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
