# Generated by Django 4.0.5 on 2022-06-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('photo', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('open_time', models.CharField(max_length=64)),
                ('avg_time_spent', models.PositiveIntegerField(default=60)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('category', models.ManyToManyField(to='tourguideapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('POI', 'Point of Interest'), ('ROU', 'Route')], max_length=3)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='tourguideapi.plan')),
            ],
        ),
    ]
