# Generated by Django 4.0.5 on 2022-06-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguideapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
