# Generated by Django 4.0.5 on 2022-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguideapi', '0003_plan_created_at_pointofinterest_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='category',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='category',
            field=models.CharField(choices=[('NA', 'Nature'), ('WE', 'Wellness'), ('LA', 'Landmark'), ('CU', 'Culinary'), ('MG', 'Museums & Galleries')], default='MG', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
