# Generated by Django 4.0.5 on 2022-06-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguideapi', '0004_remove_pointofinterest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='seq',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
