# Generated by Django 4.0.5 on 2022-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguideapi', '0005_planitem_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='ticket_url',
            field=models.TextField(default='https://www.google.com/'),
        ),
    ]
